### ISSUE TITLE
Headers names lowercased

### ISSUE THREAD

**Issue by mathieucollet** [nuxt-community/proxy-module#93]
Hello everyone,

I have a problem when I set up the proxy.

``` javascript
// Axios
axios: {
  proxy: true,
},

// Proxy
proxy: {
  '/api': {
    target: process.env.NUXT_ENV_BACKEND_API,
    pathRewrite: { '^/api': '/' },
    changeOrigin: false,
  },
},
```

The names of the Headers (Authorization, Host, etc...) are minuscule and causes errors on the back side which does not find the Headers it expects.

I may be doing a bad manipulation, but I'm lost.

From (expected result):
![image](https://user-images.githubusercontent.com/27346517/105069607-77f93080-5a82-11eb-82d7-ac6cd426061e.png)

After (with axios proxy true):
![image](https://user-images.githubusercontent.com/27346517/105069636-847d8900-5a82-11eb-8a45-db3add6b8e96.png)

**Comment by mathieucollet** [comment]
Thanks @Atinux for your time you took to answer me.

As you suggested, i tried to add the option `preserveHeaderKeyCase: true` but it doesn't change back my headers names.

Again, i'm maybe doing something wrong.

**Comment by pi0** [comment]
Hi. Actually this is NodeJS behavior that makes incoming header names to lowercase since by [rfc7230#section-3.2](https://tools.ietf.org/html/rfc7230#section-3.2) headers are case-incentive and this behavior allows having duplicate headers with different case. Proxy module option is meant for **response** handling and it is recommended not changing it to avoid inconsistency.
